Convert tabs to spaces and general tidying

diff --git a/pkg/initMonocle b/pkg/initMonocle
--- a/pkg/initMonocle
+++ b/pkg/initMonocle
@@ -17,14 +17,14 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 if [ ! -e /home/$1/.firstBoot ]; then
-	zenity --width 200 --error --title="Exiting..." --text="This program should only be run on the first boot."
-	exit 1
+    zenity --width 200 --error --title="Exiting..." --text="This program should only be run on the first boot."
+    exit 1
 elif [ ! "$(id -u)" -eq 0 ]; then
-	zenity --width 200 --error --title="Exiting..." --text="This program must be run as root."
-	exit 1
+    zenity --width 200 --error --title="Exiting..." --text="This program must be run as root."
+    exit 1
 elif [ ! -e /priv/defaultKey.bin ]; then
-	zenity --width 200 --error --title="Exiting..." --text="Key does not exist or access denied."
-	exit 1
+    zenity --width 200 --error --title="Exiting..." --text="Key does not exist or access denied."
+    exit 1
 fi
 
 source /etc/monocleOS.env
@@ -59,14 +59,14 @@ echo "100"; sleep 1
 ) | zenity --width 200 --progress --title="Setting up your PC" --text="We're just getting a few things ready for you..." --percentage=0 --auto-close --no-cancel
 
 while [[ "$password" != "$confirmPW" ]] || [[ "$password" == "" ]]; do
-	password=""
-	password=`zenity --password --title="Create a Password"`
-	confirmPW=`zenity --password --title="Confirm Your Password"`
-	if [[ "$password" != "$confirmPW" ]]; then 
-		zenity --width 200 --error --title="Creating Password Failed" --text="Passwords do not match. Please try again."
-	elif [[ "$password" == "" ]]; then 
-		zenity --width 200 --error --title="Creating Password Failed" --text="Password cannot be empty. Please try again."
-	fi
+    password=""
+    password=`zenity --password --title="Create a Password"`
+    confirmPW=`zenity --password --title="Confirm Your Password"`
+    if [[ "$password" != "$confirmPW" ]]; then 
+        zenity --width 200 --error --title="Creating Password Failed" --text="Passwords do not match. Please try again."
+    elif [[ "$password" == "" ]]; then 
+        zenity --width 200 --error --title="Creating Password Failed" --text="Password cannot be empty. Please try again."
+    fi
 done
 
 (
@@ -89,20 +89,21 @@ zenity --width 200 --info --title="Password Updated" --text="Password Added Succ
 
 zenity --width 200 --question --title="Create a Recovery Key" --text "Would you like to create a recovery key, in case you forget your password?\nIt is recommended to do this." --ok-label="Yes" --cancel-label="No" # Yes=0, No=1
 if [ $? = 0 ]; then
-	recvKey="`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`" # Use "tr -dc '[:graph:]'" for all printable characters, not including space
-	(
-	echo "25"; sleep 1
-	echo "# Adding recovery key..."; echo -e "$password" | cryptsetup luksKillSlot /dev/disk/by-uuid/$luksUUID 1 # This should fail, but just in case - don't tell user
-	echo "50"; sleep 1
-	echo "# Adding recovery key..."; echo -e "$password\n$recvKey" | cryptsetup luksAddKey -q /dev/disk/by-uuid/$luksUUID --key-slot 1 || { zenity --width 200 --error --title="Adding a Recovery Key Failed" --text="Unable to add a recovery key."; exit 1; }
-	echo "60"; sleep 1
-	echo "# Adding recovery key..."; echo -e "recovery:$recvKey" | chpasswd || { zenity --width 200 --error --title="Adding a Recovery Key Failed" --text="Unable to add a recovery key."; exit 1; }
-	echo "75"; sleep 1
-	echo "# Saving recovery key..."; echo -e "Date: `date +'%d/%m/%y %H:%M:%S'`\nYour monocleOS recovery key for $HOSTNAME is:\n\n\t$recvKey\n\nPrint this document and keep it in a safe place." > /home/$1/Recovery_Key_${HOSTNAME}_`date +'%d%m%y%H%M%S'`.txt || { zenity --width 200 --error --title="Adding a Recovery Key Failed" --text="Unable to add a recovery key."; exit 1; }
-	echo "100"; sleep 1
-	zenity --width 200 --info --title="Recovery Key Added" --text="Success! The key is stored in your files. Please print this document and keep it in a safe place."
-	) | zenity --width 200 --progress --title="Creating Recovery Key" --text="Please wait..." --percentage=0 --auto-close --no-cancel
+    recvKey="`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`" # Use "tr -dc '[:graph:]'" for all printable characters, not including space
+    (
+    echo "25"; sleep 1
+    echo "# Adding recovery key..."; echo -e "$password" | cryptsetup luksKillSlot /dev/disk/by-uuid/$luksUUID 1 # This should fail, but just in case - don't tell user
+    echo "50"; sleep 1
+    echo "# Adding recovery key..."; echo -e "$password\n$recvKey" | cryptsetup luksAddKey -q /dev/disk/by-uuid/$luksUUID --key-slot 1 || { zenity --width 200 --error --title="Adding a Recovery Key Failed" --text="Unable to add a recovery key."; exit 1; }
+    echo "60"; sleep 1
+    echo "# Adding recovery key..."; echo -e "recovery:$recvKey" | chpasswd || { zenity --width 200 --error --title="Adding a Recovery Key Failed" --text="Unable to add a recovery key."; exit 1; }
+    echo "75"; sleep 1
+    echo "# Saving recovery key..."; echo -e "Date: `date +'%d/%m/%y %H:%M:%S'`\nYour monocleOS recovery key for $HOSTNAME is:\n\n\t$recvKey\n\nPrint this document and keep it in a safe place." > /home/$1/Recovery_Key_${HOSTNAME}_`date +'%d%m%y%H%M%S'`.txt || { zenity --width 200 --error --title="Adding a Recovery Key Failed" --text="Unable to add a recovery key."; exit 1; }
+    echo "100"; sleep 1
+    zenity --width 200 --info --title="Recovery Key Added" --text="Success! The key is stored in your files. Please print this document and keep it in a safe place."
+    ) | zenity --width 200 --progress --title="Creating Recovery Key" --text="Please wait..." --percentage=0 --auto-close --no-cancel
 fi
 
 rm /home/$1/.firstBoot
-sed -i '/initMonocle/d' /etc/sudoers.d/monocleOS; visudo -cf /etc/sudoers.d/monocleOS || rm /etc/sudoers.d/monocleOS # Disallow this script from being executed by user again
+# Disallow this script from being executed by user again
+sed -i '/initMonocle/d' /etc/sudoers.d/monocleOS; visudo -cf /etc/sudoers.d/monocleOS || rm /etc/sudoers.d/monocleOS
diff --git a/pkg/tips-service b/pkg/tips-service
--- a/pkg/tips-service
+++ b/pkg/tips-service
@@ -22,57 +22,57 @@ urgency="normal"
 
 
 if [[ ! -f /home/$USER/.config/monocleOS/tips-service.conf ]]; then
-	# Defaults
-	periodicTips=1
-	periodicTipsFreq=120
-	applicationTips=1
+    # Defaults
+    periodicTips=1
+    periodicTipsFreq=120
+    applicationTips=1
 else
-	# User Preferences
-	source /home/$USER/.config/monocleOS/tips-service.conf
+    # User Preferences
+    source /home/$USER/.config/monocleOS/tips-service.conf
 fi
 
-## Daemon
+# == Daemon ==
 function funcDaemon {
-	# Random UI Tips
-	while [[ $periodicTips = 1 ]]; do
-		# Array must be defined in while loop for dynamic content
-		tipsArray=("You can turn off these helpful tips by opening Settings, then selecting Hints & Tips." "If a program is misbehaving, you can force close it by right clicking on the cross in the top-right." "By clicking on the window icons at the top-right of your screen, you can change the layout of windows." "Did you know that you can launch the on-screen magnifier by clicking on the magnifier icon." "Get Creative. Personalise your PC by opening Settings and selecting Themes & Personalisation." "It's not you; it's me. If some things are difficult to read, you can change the system font size in Settings, then Themes & Personalisation." "Not your favourite colour? Change your system's appearance in Settings  Themes & Personalisation" "Speakers too quiet? You can change the volume by scrolling on the speaker icon on the top bar - click to mute. More advanced sound settings are found in the Settings application." "Want to start up where you left off? Try putting your PC to sleep instead of powering off by clicking the Sleep icon." "Just a head's up, your PC $(/usr/bin/monocleOS --freeSpaceCheck Home)" "monocleOS is compatible with most external peripheral devices, such as mice, keyboards and cameras." "Make sure to create a recovery key, in case you forget your password. Add a recovery key in Settings  Advanced  Recovery, then Add a Recovery Key." "monocleOS cannot protect you from all evil masterminds. Be careful who you give personal data to; if something looks fishy, stay away from it." "Rarely use a certain application? Go to Settings, then select Add/Remove Programs." "To change your background image, go to Settings  Themes & Personalisation, then select Change your Wallpaper.")
-		sleep ${periodicTipsFreq}m
-		notification="${tipsArray[$RANDOM % ${#tipsArray[@]}]}" ## Set notification to random element in array
-		notify-send -u $urgency -t $timeout -a "$appName" "$notification"
-	done
+    # Random UI Tips
+    while [[ $periodicTips = 1 ]]; do
+        # Array must be defined in while loop for dynamic content
+        tipsArray=("You can turn off these helpful tips by opening Settings, then selecting Hints & Tips." "If a program is misbehaving, you can force close it by right clicking on the cross in the top-right." "By clicking on the window icons at the top-right of your screen, you can change the layout of windows." "Did you know that you can launch the on-screen magnifier by clicking on the magnifier icon." "Get Creative. Personalise your PC by opening Settings and selecting Themes & Personalisation." "It's not you; it's me. If some things are difficult to read, you can change the system font size in Settings, then Themes & Personalisation." "Not your favourite colour? Change your system's appearance in Settings  Themes & Personalisation" "Speakers too quiet? You can change the volume by scrolling on the speaker icon on the top bar - click to mute. More advanced sound settings are found in the Settings application." "Want to start up where you left off? Try putting your PC to sleep instead of powering off by clicking the Sleep icon." "Just a head's up, your PC $(/usr/bin/monocleOS --freeSpaceCheck Home)" "monocleOS is compatible with most external peripheral devices, such as mice, keyboards and cameras." "Make sure to create a recovery key, in case you forget your password. Add a recovery key in Settings  Advanced  Recovery, then Add a Recovery Key." "monocleOS cannot protect you from all evil masterminds. Be careful who you give personal data to; if something looks fishy, stay away from it." "Rarely use a certain application? Go to Settings, then select Add/Remove Programs." "To change your background image, go to Settings  Themes & Personalisation, then select Change your Wallpaper.")
+        sleep ${periodicTipsFreq}m
+        notification="${tipsArray[$RANDOM % ${#tipsArray[@]}]}" # Set notification to random element in array
+        notify-send -u $urgency -t $timeout -a "$appName" "$notification"
+    done
 }
 
-## Application Tips
+# == Application Tips ==
 function funcApp {
-	if [[ $applicationTips = 1 ]]; then
-		declare -A appTipsArray=(["lock"]="To unlock your PC, type your password and press Enter." ["office"]="In Office, you can write a letter, create a spreadsheet, or even express your artistic side with Draw." ["magnifier"]="To use the screen magnifier, move the cursor over the magnifier then hold the left mouse button while moving your mouse around the screen. To close the magnifier, click on its window and exit as normal." ["settings"]="Select an option, then click OK - or press Enter. Your choice." ["web"]="Simply type in your search query, then press Enter.")
-		app="${1,,}"
-		match=0
-		for arrayApp in "${!appTipsArray[@]}"; do # Compare given argument with keys of appTipsArray
-			if [[ $arrayApp = "$app" ]]; then
-				match=1
-				break
-			fi
-		done
-		if [[ $match = 0 ]]; then
-			echo "Invalid application identifier."
-			exit 1
-		elif [[ $match = 1 ]]; then
-			notify-send -u $urgency -t $timeout -a "$appName" "${appTipsArray[$app]}"
-		fi
-	fi
-	exit
+    if [[ $applicationTips = 1 ]]; then
+        declare -A appTipsArray=(["lock"]="To unlock your PC, type your password and press Enter." ["office"]="In Office, you can write a letter, create a spreadsheet, or even express your artistic side with Draw." ["magnifier"]="To use the screen magnifier, move the cursor over the magnifier then hold the left mouse button while moving your mouse around the screen. To close the magnifier, click on its window and exit as normal." ["settings"]="Select an option, then click OK - or press Enter. Your choice." ["web"]="Simply type in your search query, then press Enter.")
+        app="${1,,}"
+        match=0
+        for arrayApp in "${!appTipsArray[@]}"; do # Compare given argument with keys of appTipsArray
+            if [[ $arrayApp = "$app" ]]; then
+                match=1
+                break
+            fi
+        done
+        if [[ $match = 0 ]]; then
+            echo "Invalid application identifier."
+            exit 1
+        elif [[ $match = 1 ]]; then
+            notify-send -u $urgency -t $timeout -a "$appName" "${appTipsArray[$app]}"
+        fi
+    fi
+    exit
 }
 
 case "$1" in
-	--daemon)
-		funcDaemon
-		;;
-	--app)
-		funcApp $2
-		;;
-	*)
-		echo $"Usage: $0 --daemon | --app [application identifier]."
-		exit 1
+    --daemon)
+        funcDaemon
+        ;;
+    --app)
+        funcApp $2
+        ;;
+    *)
+        echo $"Usage: $0 --daemon | --app [application identifier]."
+        exit 1
 esac
